/**
 * @file eslint.config.js
 * @description ESLint flat configuration for the whole repo. Authored as CommonJS, like every
 * other file here — this project has no build step and `eslint.config.js` must not become the one
 * thing that needs one.
 *
 * Policy: this is a DEFECT check, not a style check. The repo's consistency has been maintained by
 * discipline and reviews for its whole life; a linter arriving now to reformat it would produce a
 * huge diff and catch nothing. So the rule set is `@eslint/js` `recommended` plus the handful of
 * correctness rules named below, and anything that is merely a taste question stays off.
 *
 * Every rule that is relaxed below is relaxed HERE, at the policy level, with the reason written
 * down — not by sprinkling inline disables through the source. If a relaxation ever stops being
 * true of the codebase, this file is the one place to tighten it.
 */

'use strict';

const js = require('@eslint/js');
const globals = require('globals');

/**
 * The correctness rules the project enforces on top of `recommended`, shared by every block below
 * so that no area of the repo is quietly held to a weaker standard.
 */
const CORRECTNESS_RULES = {
    // A dead local binding hides a real bug — a renamed variable, a result that was meant to be
    // returned. Kept on for variables; the two exemptions below are argued individually.
    'no-unused-vars': ['error', {
        // Parameters are exempt. Every unused parameter in this repo is a SIGNATURE being
        // documented, not a leftover: `resolveCustomTextEditor(document, webviewPanel, token)`
        // matches the VS Code API, `Module._load(request, parent, isMain)` matches Node's (and
        // forwards `arguments`), `classifyCaretContext(code, position, pou, method, symbolIndex)`
        // states its call contract in JSDoc, and `groupRootsByProject`'s `folderPaths` carries a
        // JSDoc note saying it is kept deliberately for a future multi-root workspace. Renaming
        // those to `_token` / `_symbolIndex` would degrade the documentation to satisfy a linter.
        args: 'none',
        // Same call, for the same reason. ESLint 9 changed this default to 'all', which flagged 97
        // sites — the repo's pervasive `try { … } catch (e) { <deliberate fallback> }` idiom, where
        // the binding is named for readability at the catch site even when the body does not read
        // it. Ninety-seven renames to `_e` would catch no defect. Empty catch BLOCKS are still
        // caught, by `no-empty` from `recommended`.
        caughtErrors: 'none',
        ignoreRestSiblings: true
    }],
    'no-unreachable': 'error',
    'no-fallthrough': 'error',
    // `smart` on purpose. A blind `==` -> `===` rewrite is a behaviour change, and the `== null`
    // idiom (null OR undefined in one test) is used deliberately here. `smart` permits that idiom
    // and comparisons of two literals of the same type, and flags the rest.
    eqeqeq: ['error', 'smart'],
    'no-shadow': 'error',
    'no-constant-condition': 'error',

    // OFF, deliberately. All ten occurrences in the repo are redundant-but-intentional escapes
    // inside character classes in lexer/tokenizer regexes: `\-` written so it can never read as a
    // range (`[0-9a-zA-Z_#:.\-]`, `[A-Za-z0-9_+.\-]`), `\/` inside `[\/\\]` and in the Monarch
    // operator class, `\*` in the block-comment states. None is a defect; every one of them sits in
    // a regex where an "obviously safe" cosmetic edit is how a lexer quietly starts matching
    // something else. The rule buys nothing here and would cost a regex audit, so it is off at the
    // policy level rather than silenced ten times inline.
    'no-useless-escape': 'off'
};

module.exports = [
    {
        // Nothing generated, vendored or foreign is linted. `media/monaco-editor/` is the big one:
        // it is vendored Monaco (the offline constraint), it is not ours to change, and walking it
        // makes a lint run take minutes instead of a second.
        ignores: [
            'node_modules/',
            'media/monaco-editor/',
            // Vendored third-party skill scripts, not project source.
            '.claude/skills/',
            // Git-ignored local playground; nothing in it is tracked.
            'scratch/',
            // The synthetic TwinCAT project (ST/XML fixtures, no JS of ours) and the plan documents.
            'sample/',
            'docs/',
            // Generated by test/browser/build.js.
            'test/browser/out/',
            '*.vsix'
        ]
    },

    js.configs.recommended,

    {
        // The default for the repo: CommonJS running on Node (extension host, LSP server, test
        // harnesses, dev scripts). `module`/`require`/`__dirname` are globals, not imports.
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: {
                ...globals.node
            }
        },
        rules: CORRECTNESS_RULES
    },

    {
        // `media/*.js` is DUAL-MODE: the webview loads each file with a plain `<script>` tag, and
        // the Node harnesses in `test/` `require()` the same file through the shim at its bottom.
        // Both sets of globals are therefore legitimate in one file, and a config that offered only
        // one of them would flag the other half of every module as undefined.
        //
        // Non-recursive on purpose — `media/monaco-editor/` is ignored above and must stay so.
        files: ['media/*.js'],
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.browser,
                // Injected by the Monaco loader (`media/monaco-editor/vs/loader.js`) and by the
                // VS Code webview host respectively; neither is declared in any file we own.
                monaco: 'readonly',
                require: 'readonly',
                define: 'readonly',
                acquireVsCodeApi: 'readonly',
                // The other side of the dual-mode shim: each of these modules assigns itself onto
                // the webview's global object (`root.peekUri = factory()`), and `media/editor.js`
                // reaches them by that name because the webview loads them as separate <script>
                // tags. Under Node the same files are `require`d instead, so the assignment ESLint
                // would otherwise have to see never happens in the file being linted.
                pendingEditsCore: 'readonly',
                diagnosticMarkers: 'readonly',
                stFolding: 'readonly',
                peekUri: 'readonly'
            }
        }
    },

    {
        // The browser harnesses drive a real Chromium through Playwright: the file is a Node
        // script, but the function bodies handed to `page.evaluate()` run in the page and use
        // browser globals. One file, both environments, same as `media/*.js` above.
        files: ['test/browser/**/*.js'],
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.browser,
                monaco: 'readonly'
            }
        }
    }
];
