/**
 * @file test/browser/build.js
 * @description Builds a browser-runnable harness for media/editor.js, so the ONE half of the
 * references-peek path that no Node test can reach — the webview — can actually be driven.
 *
 * The page is generated by calling the REAL getHtmlForWebview() with a stubbed `vscode` module, not
 * by hand-copying its markup: a hand copy silently stops matching production the first time the
 * template changes, which would make this harness prove something about a page nobody ships.
 *
 * Two substitutions, and only two:
 *   - `acquireVsCodeApi()` is stubbed to record outgoing postMessages and answer bridge requests
 *     from a canned fixture, which is what stands in for the extension host;
 *   - the webview CSP is dropped, because it names `vscode-webview://` sources that do not exist
 *     over http. Everything else — the loader, the worker blob, the AMD baseUrl, editor.js itself —
 *     is production code running unmodified.
 *
 * Fixtures come from the real sample project through the real parser, and the reference payload is
 * built by the same steps customEditorProvider.js takes, so the numbers the harness asserts are the
 * numbers the extension would send.
 *
 * Run: node test/browser/build.js   (writes ./out/index.html + ./out/fixture.json)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const Module = require('module');

const REPO = path.resolve(__dirname, '..', '..');
const OUT = path.join(__dirname, 'out');

// ---------------------------------------------------------------------------------------------
// 1. Stub `vscode` so customEditorProvider.js can be required outside the extension host.
// ---------------------------------------------------------------------------------------------
const vscodeStub = {
    Uri: {
        joinPath: (base, ...parts) => ({ fsPath: path.join(base.fsPath, ...parts), _parts: parts }),
        parse: (s) => ({ toString: () => s, fsPath: s })
    },
    // Nothing below is reached by getHtmlForWebview; present so the require does not explode.
    window: {}, workspace: {}, commands: {}, EventEmitter: class { }, Disposable: class { }
};
const realLoad = Module._load;
Module._load = function (request, parent, isMain) {
    if (request === 'vscode') return vscodeStub;
    return realLoad.apply(this, arguments);
};

const { TwinCatCustomEditorProvider } = require(path.join(REPO, 'src', 'customEditorProvider.js'));
const { parseTwinCatXml } = require(path.join(REPO, 'src', 'xmlParser.js'));
const { convertXmlToSt } = require(path.join(REPO, 'src', 'stConverter.js'));
const lspParser = require(path.join(REPO, 'src', 'lsp', 'parser.js'));
const { indexXmlObject } = require(path.join(REPO, 'src', 'lsp', 'xmlIndexer.js'));
const features = require(path.join(REPO, 'src', 'lsp', 'features.js'));

// ---------------------------------------------------------------------------------------------
// 2. Generate the page exactly as the extension would, then swap the two stubs in.
// ---------------------------------------------------------------------------------------------
const provider = new TwinCatCustomEditorProvider(
    { extensionUri: { fsPath: REPO }, extensionPath: REPO, subscriptions: [] },
    {}
);
// ABSOLUTE urls, as the real asWebviewUri returns (https://file+.vscode-resource.vscode-cdn.net/…).
// Root-relative paths look equivalent but are not: the Monaco worker runs from a blob: URL, which
// has no base to resolve them against, and its NLS strings 404 with "Failed trying to load default
// language strings" — the same symptom HANDOFF records for getting the AMD baseUrl wrong.
const ORIGIN = process.env.HARNESS_ORIGIN || 'http://localhost:8123';
const fakeWebview = {
    cspSource: ORIGIN,
    asWebviewUri: (uri) => ORIGIN + '/' + path.relative(REPO, uri.fsPath).split(path.sep).join('/')
};
let html = provider.getHtmlForWebview(fakeWebview);

// The webview CSP names vscode-webview: sources that do not exist over http.
html = html.replace(/<meta http-equiv="Content-Security-Policy"[^>]*>/, '<!-- CSP dropped: harness runs over http -->');

// The extension host stand-in. Inserted before editor.js so acquireVsCodeApi exists when it runs.
const stub = `
    <script>
    (function () {
        window.__harness = { sent: [], fixture: null, ready: false };
        window.acquireVsCodeApi = function () {
            return {
                postMessage: function (msg) {
                    window.__harness.sent.push(msg);
                    var f = window.__harness.fixture;
                    if (!f || !msg || !msg.requestId) return;
                    // Answer bridge requests the way the extension host does.
                    if (msg.type === 'custom/references') {
                        window.postMessage({
                            type: 'custom/referencesResponse',
                            requestId: msg.requestId,
                            references: f.references,
                            panes: f.panes
                        }, '*');
                    } else if (msg.type === 'custom/diagnostics') {
                        window.postMessage({ type: 'custom/diagnosticsResponse', requestId: msg.requestId, diagnostics: [] }, '*');
                    } else if (msg.type === 'custom/completions') {
                        window.postMessage({ type: 'custom/completionsResponse', requestId: msg.requestId, suggestions: [] }, '*');
                    } else if (msg.type === 'custom/definition') {
                        window.postMessage({ type: 'custom/definitionResponse', requestId: msg.requestId, definition: null }, '*');
                    }
                },
                getState: function () { return {}; },
                setState: function () { }
            };
        };
        window.__harnessInit = function (fixture) {
            window.__harness.fixture = fixture;
            window.postMessage(fixture.init, '*');
            window.__harness.ready = true;
        };
    })();
    </script>
`;
const editorTag = `<script src="${ORIGIN}/media/editor.js"></script>`;
html = html.replace(editorTag, stub + '\n' + editorTag);
if (!html.includes('__harnessInit')) throw new Error('failed to inject the harness stub — did the script tag change?');

// ---------------------------------------------------------------------------------------------
// 3. Fixtures: the init payload and the reference payload, both from the real sample.
// ---------------------------------------------------------------------------------------------
function walk(dir, out = []) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, e.name);
        if (e.isDirectory()) walk(p, out);
        else if (/\.(TcPOU|TcGVL|TcDUT|TcIO)$/.test(e.name)) out.push(p);
    }
    return out;
}
const toUri = p => 'file:///' + p.split(path.sep).join('/');

const files = walk(path.join(REPO, 'sample'));
lspParser.clearWorkspaceIndex();
const index = lspParser.getWorkspaceSymbolIndex();
const byName = {}, byUri = {};
for (const file of files) {
    const xml = fs.readFileSync(file, 'utf8');
    const uri = toUri(file);
    const node = indexXmlObject(index, xml, uri);
    if (node) byName[node.name] = { file, uri, xml };
    byUri[uri.toLowerCase()] = { file, uri, xml };
}

// Mirrors of the two extension helpers this path depends on.
function paneTextFromUnit(lines, lineMap, componentId, pane) {
    const blocks = lineMap && lineMap[componentId];
    if (!blocks) return null;
    const block = pane === 'decl' ? blocks.decl : blocks.impl;
    if (!block || !block.start) return null;
    return lines.slice(block.start - 1, block.end).join('\n');
}
function absoluteToLocal(lineMap, abs0) {
    const l = abs0 + 1;
    for (const c of Object.keys(lineMap)) {
        const b = lineMap[c];
        if (b.decl && b.decl.start && l >= b.decl.start && l <= b.decl.end) return { componentId: c, pane: 'decl', localLine0: l - b.decl.start };
        if (b.impl && b.impl.start && l >= b.impl.start && l <= b.impl.end) return { componentId: c, pane: 'impl', localLine0: l - b.impl.start };
    }
    return null;
}
function peekPath(fileUri, componentId, pane) {
    let base = 'object';
    try { base = decodeURIComponent(String(fileUri).split(/[\\/]/).pop() || base); } catch (e) { /* default */ }
    const member = componentId === 'root' ? 'root' : String(componentId).replace(/^(method|prop|action|trans|get|set)_/i, '');
    return '/' + member + '.' + pane + '/' + base;   // file LAST — Monaco bolds the basename
}

const SYMBOL = 'FB_Cylinder';
const active = byName[SYMBOL];
const parsed = parseTwinCatXml(active.xml);
const unit = convertXmlToSt(parsed, { raw: true });
const unitLines = unit.stText.split('\n');
const declLine = unitLines.findIndex(l => /FUNCTION_BLOCK\s+FB_Cylinder/.test(l));
const refs = features.provideReferences(
    unit.stText, { line: declLine, character: unitLines[declLine].indexOf(SYMBOL) + 1 }, index, active.uri
) || [];

const stCache = new Map();
const getSt = (uri) => {
    const k = uri.toLowerCase();
    if (stCache.has(k)) return stCache.get(k);
    let r = null;
    if (k === active.uri.toLowerCase()) r = { st: unit, lines: unitLines };
    else if (byUri[k]) { const c = convertXmlToSt(parseTwinCatXml(byUri[k].xml), { raw: true }); r = { st: c, lines: c.stText.split('\n') }; }
    stCache.set(k, r);
    return r;
};
const paneByKey = new Map();
const references = [];
for (const r of refs) {
    const entry = getSt(r.uri);
    if (!entry) continue;
    const loc = absoluteToLocal(entry.st.lineMap, r.range.start.line);
    if (!loc) continue;
    const key = r.uri.toLowerCase() + '::' + loc.componentId + '::' + loc.pane;
    if (!paneByKey.has(key)) {
        const text = paneTextFromUnit(entry.lines, entry.st.lineMap, loc.componentId, loc.pane);
        if (text !== null) {
            paneByKey.set(key, {
                key, uri: r.uri, componentId: loc.componentId, pane: loc.pane,
                path: peekPath(r.uri, loc.componentId, loc.pane), text
            });
        }
    }
    references.push({
        sameFile: r.uri.toLowerCase() === active.uri.toLowerCase(),
        uri: r.uri, paneKey: key, componentId: loc.componentId, pane: loc.pane,
        line: loc.localLine0, startCharacter: r.range.start.character, endCharacter: r.range.end.character
    });
}

const fixture = {
    symbol: SYMBOL,
    init: {
        type: 'init',
        fileUri: active.uri,
        filename: path.basename(active.file),
        data: { rootType: parsed.rootType || 'POU', components: parsed.components },
        splitterRatio: 50,
        isAutoSync: true,
        selectId: 'root'
    },
    references,
    panes: Array.from(paneByKey.values()),
    // What the assertions expect, derived here rather than hardcoded in the test.
    expect: {
        totalRefs: references.length,
        crossFileRefs: references.filter(r => !r.sameFile).length,
        panes: paneByKey.size,
        distinctFiles: new Set(Array.from(paneByKey.keys()).map(k => k.split('::')[0])).size
    }
};

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), html, 'utf8');
fs.writeFileSync(path.join(OUT, 'fixture.json'), JSON.stringify(fixture, null, 2), 'utf8');

console.log('harness written to', OUT);
console.log('fixture:', JSON.stringify(fixture.expect));
console.log('panes:', fixture.panes.map(p => p.path).join(', '));
