/**
 * @file test/browser/build.js
 * @description Builds a browser-runnable harness for media/editor.js, so the ONE half of the
 * references-peek path that no Node test can reach — the webview — can actually be driven.
 *
 * The page is generated by calling the REAL getHtmlForWebview() with a stubbed `vscode` module, not
 * by hand-copying its markup: a hand copy silently stops matching production the first time the
 * template changes, which would make this harness prove something about a page nobody ships.
 *
 * Two substitutions, and only two:
 *   - `acquireVsCodeApi()` is stubbed to record outgoing postMessages and answer bridge requests
 *     from a canned fixture, which is what stands in for the extension host;
 *   - the webview CSP is dropped, because it names `vscode-webview://` sources that do not exist
 *     over http. Everything else — the loader, the worker blob, the AMD baseUrl, editor.js itself —
 *     is production code running unmodified.
 *
 * Fixtures come from the real sample project through the real parser, and the reference payload is
 * built by the same steps customEditorProvider.js takes, so the numbers the harness asserts are the
 * numbers the extension would send.
 *
 * Run: node test/browser/build.js   (writes ./out/index.html + ./out/fixture.json)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const Module = require('module');

const REPO = path.resolve(__dirname, '..', '..');
const OUT = path.join(__dirname, 'out');

// ---------------------------------------------------------------------------------------------
// 1. Stub `vscode` so customEditorProvider.js can be required outside the extension host.
// ---------------------------------------------------------------------------------------------
const vscodeStub = {
    Uri: {
        joinPath: (base, ...parts) => ({ fsPath: path.join(base.fsPath, ...parts), _parts: parts }),
        parse: (s) => ({ toString: () => s, fsPath: s })
    },
    // Nothing below is reached by getHtmlForWebview; present so the require does not explode.
    window: {}, workspace: {}, commands: {}, EventEmitter: class { }, Disposable: class { }
};
const realLoad = Module._load;
Module._load = function (request, parent, isMain) {
    if (request === 'vscode') return vscodeStub;
    return realLoad.apply(this, arguments);
};

const { TwinCatCustomEditorProvider } = require(path.join(REPO, 'src', 'customEditorProvider.js'));
const { parseTwinCatXml } = require(path.join(REPO, 'src', 'xmlParser.js'));
const { convertXmlToSt } = require(path.join(REPO, 'src', 'stConverter.js'));
const lspParser = require(path.join(REPO, 'src', 'lsp', 'parser.js'));
const { indexXmlObject } = require(path.join(REPO, 'src', 'lsp', 'xmlIndexer.js'));
const features = require(path.join(REPO, 'src', 'lsp', 'features.js'));

// ---------------------------------------------------------------------------------------------
// 2. Generate the page exactly as the extension would, then swap the two stubs in.
// ---------------------------------------------------------------------------------------------
const provider = new TwinCatCustomEditorProvider(
    { extensionUri: { fsPath: REPO }, extensionPath: REPO, subscriptions: [] },
    {}
);
// ABSOLUTE urls, as the real asWebviewUri returns (https://file+.vscode-resource.vscode-cdn.net/…).
// Root-relative paths look equivalent but are not: the Monaco worker runs from a blob: URL, which
// has no base to resolve them against, and its NLS strings 404 with "Failed trying to load default
// language strings" — the same symptom HANDOFF records for getting the AMD baseUrl wrong.
const ORIGIN = process.env.HARNESS_ORIGIN || 'http://localhost:8123';
const fakeWebview = {
    cspSource: ORIGIN,
    asWebviewUri: (uri) => ORIGIN + '/' + path.relative(REPO, uri.fsPath).split(path.sep).join('/')
};
let html = provider.getHtmlForWebview(fakeWebview);

// The webview CSP names vscode-webview: sources that do not exist over http.
html = html.replace(/<meta http-equiv="Content-Security-Policy"[^>]*>/, '<!-- CSP dropped: harness runs over http -->');

// The extension host stand-in. Inserted before editor.js so acquireVsCodeApi exists when it runs.
const stub = `
    <script>
    (function () {
        window.__harness = { sent: [], fixture: null, ready: false, definitionEnabled: false };
        window.acquireVsCodeApi = function () {
            return {
                postMessage: function (msg) {
                    window.__harness.sent.push(msg);
                    var f = window.__harness.fixture;
                    if (!f || !msg || !msg.requestId) return;
                    // Answer bridge requests the way the extension host does.
                    if (msg.type === 'custom/references') {
                        window.postMessage({
                            type: 'custom/referencesResponse',
                            requestId: msg.requestId,
                            references: f.references,
                            panes: f.panes
                        }, '*');
                    } else if (msg.type === 'custom/diagnostics') {
                        window.postMessage({ type: 'custom/diagnosticsResponse', requestId: msg.requestId, diagnostics: [] }, '*');
                    } else if (msg.type === 'custom/completions') {
                        window.postMessage({ type: 'custom/completionsResponse', requestId: msg.requestId, suggestions: [] }, '*');
                    } else if (msg.type === 'custom/definition') {
                        // Off unless a test arms it: Monaco calls definition providers speculatively
                        // (word selection, ctrl-hover), and every other assertion here is about the
                        // references peek, which must not start answering definitions as a side effect.
                        window.postMessage({
                            type: 'custom/definitionResponse',
                            requestId: msg.requestId,
                            definition: window.__harness.definitionEnabled ? (f.definition || null) : null
                        }, '*');
                    }
                },
                getState: function () { return {}; },
                setState: function () { }
            };
        };
        window.__harnessInit = function (fixture) {
            window.__harness.fixture = fixture;
            window.postMessage(fixture.init, '*');
            window.__harness.ready = true;
        };
    })();
    </script>
`;
const editorTag = `<script src="${ORIGIN}/media/editor.js"></script>`;
html = html.replace(editorTag, stub + '\n' + editorTag);
if (!html.includes('__harnessInit')) throw new Error('failed to inject the harness stub — did the script tag change?');

// ---------------------------------------------------------------------------------------------
// 3. Fixtures: the init payload and the reference payload, both from the real sample.
// ---------------------------------------------------------------------------------------------
function walk(dir, out = []) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, e.name);
        if (e.isDirectory()) walk(p, out);
        else if (/\.(TcPOU|TcGVL|TcDUT|TcIO)$/.test(e.name)) out.push(p);
    }
    return out;
}
const toUri = p => 'file:///' + p.split(path.sep).join('/');

const files = walk(path.join(REPO, 'sample'));
lspParser.clearWorkspaceIndex();
const index = lspParser.getWorkspaceSymbolIndex();
const byName = {}, byUri = {};
for (const file of files) {
    const xml = fs.readFileSync(file, 'utf8');
    const uri = toUri(file);
    const node = indexXmlObject(index, xml, uri);
    if (node) byName[node.name] = { file, uri, xml };
    byUri[uri.toLowerCase()] = { file, uri, xml };
}

// Mirrors of the two extension helpers this path depends on.
function paneTextFromUnit(lines, lineMap, componentId, pane) {
    const blocks = lineMap && lineMap[componentId];
    if (!blocks) return null;
    const block = pane === 'decl' ? blocks.decl : blocks.impl;
    if (!block || !block.start) return null;
    return lines.slice(block.start - 1, block.end).join('\n');
}
function absoluteToLocal(lineMap, abs0) {
    const l = abs0 + 1;
    for (const c of Object.keys(lineMap)) {
        const b = lineMap[c];
        if (b.decl && b.decl.start && l >= b.decl.start && l <= b.decl.end) return { componentId: c, pane: 'decl', localLine0: l - b.decl.start };
        if (b.impl && b.impl.start && l >= b.impl.start && l <= b.impl.end) return { componentId: c, pane: 'impl', localLine0: l - b.impl.start };
    }
    return null;
}
function peekPath(fileUri, componentId, pane) {
    let base = 'object';
    try { base = decodeURIComponent(String(fileUri).split(/[\\/]/).pop() || base); } catch (e) { /* default */ }
    const member = componentId === 'root' ? 'root' : String(componentId).replace(/^(method|prop|action|trans|get|set)_/i, '');
    return '/' + member + '.' + pane + '/' + base;   // file LAST — Monaco bolds the basename
}

const SYMBOL = 'FB_Cylinder';
const active = byName[SYMBOL];

// Go to Definition used to land on the first occurrence of the NAME in the declaration pane rather
// than on the declaration, so the fixture needs a symbol whose name also appears higher up in that
// same pane inside a comment — the shape of the FB the user reported, whose header comment says
// "…until bDone or bError". No sample object has it, and sample/ is the diagnostics ground truth
// (generated, committed, asserted at zero), so the comment is spliced in HERE, in memory. Everything
// downstream — the parse, the ST conversion, the symbol index, provideDefinition, absoluteToLocal —
// is the real code path, so the coordinates the harness asserts on are coordinates the extension
// would really send.
// It goes BELOW the POU header rather than above it, so line 1 of the declaration pane is still
// `FUNCTION_BLOCK FB_Cylinder` and the peek assertions further down keep addressing what they did.
const DEF_SYMBOL = '_bExtended';
const DEF_COMMENT = '(*\r\n\tThe sensor image. _bExtended and _bRetracted are refreshed by Cyclic();\r\n' +
    '\tNothing else may write them.\r\n*)\r\n';
const DEF_ANCHOR = '<Declaration><![CDATA[FUNCTION_BLOCK FB_Cylinder\r\n';
if (!active.xml.includes(DEF_ANCHOR)) throw new Error('FB_Cylinder no longer starts the way the fixture expects');
active.xml = active.xml.replace(DEF_ANCHOR, DEF_ANCHOR + DEF_COMMENT);
// Re-index the edited object so the LSP answers against the same text the panes will show.
indexXmlObject(index, active.xml, active.uri);

const parsed = parseTwinCatXml(active.xml);
const unit = convertXmlToSt(parsed, { raw: true });
const unitLines = unit.stText.split('\n');
const declLine = unitLines.findIndex(l => /FUNCTION_BLOCK\s+FB_Cylinder/.test(l));
const refs = features.provideReferences(
    unit.stText, { line: declLine, character: unitLines[declLine].indexOf(SYMBOL) + 1 }, index, active.uri
) || [];

const stCache = new Map();
const getSt = (uri) => {
    const k = uri.toLowerCase();
    if (stCache.has(k)) return stCache.get(k);
    let r = null;
    if (k === active.uri.toLowerCase()) r = { st: unit, lines: unitLines };
    else if (byUri[k]) { const c = convertXmlToSt(parseTwinCatXml(byUri[k].xml), { raw: true }); r = { st: c, lines: c.stText.split('\n') }; }
    stCache.set(k, r);
    return r;
};
const paneByKey = new Map();
const references = [];
for (const r of refs) {
    const entry = getSt(r.uri);
    if (!entry) continue;
    const loc = absoluteToLocal(entry.st.lineMap, r.range.start.line);
    if (!loc) continue;
    const key = r.uri.toLowerCase() + '::' + loc.componentId + '::' + loc.pane;
    if (!paneByKey.has(key)) {
        const text = paneTextFromUnit(entry.lines, entry.st.lineMap, loc.componentId, loc.pane);
        if (text !== null) {
            paneByKey.set(key, {
                key, uri: r.uri, componentId: loc.componentId, pane: loc.pane,
                path: peekPath(r.uri, loc.componentId, loc.pane), text
            });
        }
    }
    references.push({
        sameFile: r.uri.toLowerCase() === active.uri.toLowerCase(),
        uri: r.uri, paneKey: key, componentId: loc.componentId, pane: loc.pane,
        line: loc.localLine0, startCharacter: r.range.start.character, endCharacter: r.range.end.character
    });
}

// The definition payload, built by the same steps customEditorProvider.js takes for
// custom/definition: ask the LSP from a real usage position, then map the absolute answer back to a
// component/pane/local line with absoluteToLocal. The webview must jump to THAT, not to the first
// occurrence of the name in the pane.
// Sync the document into the index first, exactly as server.js does before answering any custom
// request. Skipping it leaves the symbol carrying the XML indexer's coordinates, and the definition
// comes back pointing at a line that is not the declaration — the trap HANDOFF records under
// "Diagnostics: how to measure".
lspParser.parseAndIndexDocument(unit.stText, active.uri);
const defUseLine = unitLines.findIndex(l => new RegExp('^\\s*' + DEF_SYMBOL + '\\s*:=').test(l));
const rawDef = features.provideDefinition(
    unit.stText, { line: defUseLine, character: unitLines[defUseLine].indexOf(DEF_SYMBOL) + 1 }, index, active.uri);
const defLoc = rawDef && rawDef.range ? absoluteToLocal(unit.lineMap, rawDef.range.start.line) : null;
if (!rawDef || !defLoc) throw new Error(`could not resolve a definition for ${DEF_SYMBOL} (line ${defUseLine})`);
const definition = {
    ...rawDef,
    componentId: defLoc.componentId,
    pane: defLoc.pane,
    localLine: defLoc.localLine0
};

// Where the name appears in the comment. This is the line the old word search jumped to, so the
// assertions need it to be a real, earlier line in the same pane — not an assumption.
const declPaneLines = (paneTextFromUnit(unitLines, unit.lineMap, 'root', 'decl') || '').split('\n');
const decoyLine = declPaneLines.findIndex(l => l.includes(DEF_SYMBOL));
if (decoyLine < 0 || decoyLine >= definition.localLine) {
    throw new Error(`fixture is not the bug's shape: decoy at ${decoyLine}, declaration at ${definition.localLine}`);
}

const fixture = {
    symbol: SYMBOL,
    init: {
        type: 'init',
        fileUri: active.uri,
        filename: path.basename(active.file),
        data: { rootType: parsed.rootType || 'POU', components: parsed.components },
        splitterRatio: 50,
        isAutoSync: true,
        selectId: 'root'
    },
    references,
    panes: Array.from(paneByKey.values()),
    definition,
    // What the assertions expect, derived here rather than hardcoded in the test.
    expect: {
        totalRefs: references.length,
        crossFileRefs: references.filter(r => !r.sameFile).length,
        panes: paneByKey.size,
        distinctFiles: new Set(Array.from(paneByKey.keys()).map(k => k.split('::')[0])).size,
        definition: {
            word: DEF_SYMBOL,
            pane: definition.pane,
            declarationLine: definition.localLine,
            decoyLine: decoyLine
        }
    }
};

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), html, 'utf8');
fs.writeFileSync(path.join(OUT, 'fixture.json'), JSON.stringify(fixture, null, 2), 'utf8');

console.log('harness written to', OUT);
console.log('fixture:', JSON.stringify(fixture.expect));
console.log('panes:', fixture.panes.map(p => p.path).join(', '));
